ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: v1
  AGENT_0:
    SENSORS: [RGB_SENSOR, DEPTH_SENSOR]
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
    gpu2gpu_transfer: True  #https://github.com/facebookresearch/habitat-sim#rendering-to-gpu-tensors
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
    gpu2gpu_transfer: True  #https://github.com/facebookresearch/habitat-sim#rendering-to-gpu-tensors
TASK:
  TYPE: VLN-v0
  POSSIBLE_ACTIONS: [STOP, MOVE_FORWARD, TURN_LEFT, TURN_RIGHT, LOOK_UP, LOOK_DOWN]
  SUCCESS_DISTANCE: 3.0

  SENSORS: [INSTRUCTION_SENSOR]
  INSTRUCTION_SENSOR_UUID: rxr_instruction

  MEASUREMENTS: [
    DISTANCE_TO_GOAL,
    SUCCESS,
    SPL
  ]

  SUCCESS:
    SUCCESS_DISTANCE: 3.0
  ORACLE_SUCCESS:
    SUCCESS_DISTANCE: 3.0
  NDTW:
    GT_PATH: data/datasets/RxR_VLNCE_v0/{split}/{split}_{role}_gt.json.gz
    SUCCESS_DISTANCE: 3.0

DATASET:
  TYPE: RxR-VLN-CE-v1
  SPLIT: val_seen
  ROLES: [guide]  # "*", "guide", "follower"
  LANGUAGES: [en-US, en-IN]  #  "*", "te-IN", "hi-IN", "en-US", "en-IN"
  DATA_PATH: data/datasets/RxR_VLNCE_v0/{split}/{split}_{role}.json.gz
  SCENES_DIR: data/scene_datasets/
